query getAllStore(
  $first: ConnectionLimitInt
  $offset: Int
  $searchQuery: String
) {
  getAllStore(first: $first, offset: $offset, searchQuery: $searchQuery) {
    totalCount
    nodes{
      _id
      name
      isSeller
       roles
      storeName
      phoneNumber
      storeLogo
      profile{
        picture
        username
        firstName
        lastName
        phone
      }
    
    }
  }
}
