query getAllNewSeller(
 $PageNumber: Int
$itemPerPage: Int
$tagsId: String
) {
  getAllNewSeller( PageNumber: $PageNumber,itemPerPage: $itemPerPage, tagsId: $tagsId) {
    AccountDetail {
      _id
      name
      userId
      emailRecords {
        address
      }
      firstName
      language
      lastName
      metafields {
        namespace
      }
      picture
      updatedAt
      userId
      username
      isSeller
      storeInfo {
        storeName
        image
      }
      products {
        _id
        createdAt
        pageTitle
        tags {
          nodes {
            _id
            name
          }
        }
        title
        vendor
        originCountry
        tagIds
      }
    }
    totalPage
  }
}
