query catalogItemsQuery(
  $shopId: ID!
  $tagIds: [ID]
  $sortBy: CatalogItemSortByField
  $sortByPriceCurrencyCode: String
  $sortOrder: SortOrder
) {
  catalogItems(
    shopIds: [$shopId]
    tagIds: $tagIds
    first: 16
    sortBy: $sortBy
    sortByPriceCurrencyCode: $sortByPriceCurrencyCode
    sortOrder: $sortOrder
  ) {
    totalCount
    pageInfo {
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        _id
        ... on CatalogItemProduct {
          product {
            _id
            title
            slug
            description
            vendor
            productId
            variants {
              _id
              variantId
              optionTitle
              options {
                _id
              }
            }
            isLowQuantity
            isSoldOut
            isBackorder
            metafields {
              description
              key
              namespace
              scope
              value
              valueType
            }
            shop {
              currency {
                code
              }
            }
            pricing {
              compareAtPrice {
                displayAmount
              }
              currency {
                code
              }
              displayPrice
              minPrice
              maxPrice
            }
            media {
              URLs {
                large
              }
            }
            primaryImage {
              URLs {
                thumbnail
                small
                medium
                large
              }
            }
          }
        }
      }
    }
  }
}
