query viewer {
  viewer {
    _id
    isSeller
    storeInfo {
      storeName
    }
    addressBook {
      edges {
        node {
          _id
          address1
          address2
          city
          company
          country
          fullName
          isBillingDefault
          isCommercial
          isShippingDefault
          phone
          postal
          region
        }
      }
    }
    adminUIShops {
      _id
      name
    }
    emailRecords {
      address
    }
    name
    primaryEmailAddress
  }
}
